// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvRwK9ST3R-vBVZ_ctztyMRlc8iBgJSZI',
    appId: '1:335972269488:web:99dc8046270e7cc496ea75',
    messagingSenderId: '335972269488',
    projectId: 'e-shoppy-3304b',
    authDomain: 'e-shoppy-3304b.firebaseapp.com',
    storageBucket: 'e-shoppy-3304b.appspot.com',
    measurementId: 'G-XVMNJ79CNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEAoQ3ydy2LH33zTFuS6b6gWrbghtls4k',
    appId: '1:335972269488:android:646ffc6955a099ed96ea75',
    messagingSenderId: '335972269488',
    projectId: 'e-shoppy-3304b',
    storageBucket: 'e-shoppy-3304b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCugdmsje4fzfnw0cUqzcG6R2BOfguSSQQ',
    appId: '1:335972269488:ios:541cfb8ebc99f1c396ea75',
    messagingSenderId: '335972269488',
    projectId: 'e-shoppy-3304b',
    storageBucket: 'e-shoppy-3304b.appspot.com',
    iosBundleId: 'com.example.eShoppy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCugdmsje4fzfnw0cUqzcG6R2BOfguSSQQ',
    appId: '1:335972269488:ios:657e0a7b7823fcbf96ea75',
    messagingSenderId: '335972269488',
    projectId: 'e-shoppy-3304b',
    storageBucket: 'e-shoppy-3304b.appspot.com',
    iosBundleId: 'com.example.eShoppy.RunnerTests',
  );
}
